version: '3'

services:
  authelia:
    image: authelia/authelia
    container_name: ${APP_NAME}-authelia
    volumes:
      - ./docker/volumes/authelia/config:/config
    networks:
      - TraefikNetwork
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${APP_NAME}-router-authelia.rule=Host(`${AUTH_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}`)'
      - 'traefik.http.routers.${APP_NAME}-router-authelia.entrypoints=${TRAEFIK_ENTRYPOINT}'
      - 'traefik.http.routers.${APP_NAME}-router-authelia.tls=true'
      - 'traefik.http.routers.${APP_NAME}-router-authelia.tls.certresolver=${TRAEFIK_CERT_RESOLVER}'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTH_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: always
    environment:
      - TZ=CET
      - "AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY=deny"
      - "X_AUTHELIA_CONFIG_FILTERS=template"

  authelia-lldap:
    image: lldap/lldap:stable
    container_name: ${APP_NAME}-authelia-lldap
    restart: always
    networks:
        - TraefikNetwork
    expose:
        - 17170
        - 6360
        - 3890
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${APP_NAME}-router-lldap.rule=Host(`${LDAP_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}`)'
      - 'traefik.http.routers.${APP_NAME}-router-lldap.entrypoints=${TRAEFIK_ENTRYPOINT}'
      - 'traefik.http.routers.${APP_NAME}-router-lldap.tls=true'
      - 'traefik.http.routers.${APP_NAME}-router-lldap.tls.certresolver=${TRAEFIK_CERT_RESOLVER}'
      - 'traefik.http.services.${APP_NAME}-service.loadbalancer.server.port=17170'
    volumes:
      - "./docker/volumes/lldap:/data"
    environment:
      - "LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}"
      - "LLDAP_KEY_SEED=${LLDAP_KEY_SEED}"
      - "LLDAP_LDAP_BASE_DN=dc=${DOMAIN},dc=${DOMAIN_ENDING}"

  authelia-postgres:
    image: postgres
    container_name: ${APP_NAME}-authelia-postgres
    volumes:
      - ./docker/volumes/authelia/postgres:/var/lib/mysql
    networks:
      - TraefikNetwork
    expose:
      - 5432
    restart: unless-stopped
    environment:
      - POSTGRES_DATABASE=authelia
      - POSTGRES_USER=authelia
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=CET

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}-redis
    volumes:
      - ./docker/volumes/redis:/data
    networks:
      - TraefikNetwork
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=CET

  traefik:
    image: traefik:3.1.2
    container_name: ${APP_NAME}-traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command:
      #API Settings
      #Provider settings
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${TRAEFIK_NETWORK}"
      #EntryPaintSettings
      - "--entrypoints.${APP_NAME}-http-entrypoint.address=:80"
      - "--entrypoints.${APP_NAME}-http-entrypoint.http.redirections.entryPoint.to=${TRAEFIK_ENTRYPOINT}"
      - "--entrypoints.${APP_NAME}-http-entrypoint.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.${TRAEFIK_ENTRYPOINT}.address=:443"
      #Certifficate Settings
      - "--certificatesresolvers.${TRAEFIK_CERT_RESOLVER}.acme.tlschallenge=true"
      - "--certificatesresolvers.${TRAEFIK_CERT_RESOLVER}.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.${TRAEFIK_CERT_RESOLVER}.acme.storage=/acme/acme.json"

      #Logging
      - '--log=true'
      - '--log.level=DEBUG'

    labels:
      - "traefik.enable=true"

    volumes:
      #That Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/volumes/traefik/acme-volume:/acme
    networks:
      - TraefikNetwork

  backend:
    pid: host
    container_name: ${APP_NAME}-backend
    depends_on:
      authelia:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - AUTH_DOMAIN=${AUTH_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - MONGO_URI=mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/public?authSource=public
    networks:
        - TraefikNetwork
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${APP_NAME}-backend.rule=Host(`${APP_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.${APP_NAME}-backend.entrypoints=${TRAEFIK_ENTRYPOINT}'
      - 'traefik.http.routers.${APP_NAME}-backend.tls=true'
      - 'traefik.http.routers.${APP_NAME}-backend.tls.certresolver=${TRAEFIK_CERT_RESOLVER}'
      - 'traefik.http.routers.${APP_NAME}-backend.middlewares=authelia@docker'
      - "traefik.http.routers.${APP_NAME}-backend.middlewares=appStripPrefix"
      - "traefik.http.middlewares.appStripPrefix.stripprefix.prefixes=/api"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME}-mongodb
    restart: always
    expose:
      - 27017
    networks:
      - TraefikNetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_USERNAME}
    volumes:
      - ./docker/volumes/database:/data/db
      - ./docker/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  frontend:
    container_name: ${APP_NAME}-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BASE_URL=https://${APP_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}
        - API_URL=https://${APP_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}/api
        - AUTH_URL=https://${AUTH_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}
        - CLIENT_ID=${OIDC_CLIENT_ID}
    networks:
      - TraefikNetwork
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${APP_NAME}-frontend.rule=Host(`${APP_SUBDOMAIN}.${DOMAIN}.${DOMAIN_ENDING}`)'
      - 'traefik.http.routers.${APP_NAME}-frontend.entrypoints=${TRAEFIK_ENTRYPOINT}'
      - 'traefik.http.routers.${APP_NAME}-frontend.tls=true'
      - 'traefik.http.routers.${APP_NAME}-frontend.tls.certresolver=${TRAEFIK_CERT_RESOLVER}'


networks:
  TraefikNetwork:
    external: true
    name: ${TRAEFIK_NETWORK}